language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t valtersk/docker-kubernetes-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true valtersk/docker-kubernetes-practice npm run test